[2024-08-21T16:41:29.547+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-21T16:41:29.573+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_v2.insert_into_table manual__2024-08-21T16:40:27.534805+00:00 [queued]>
[2024-08-21T16:41:29.583+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_v2.insert_into_table manual__2024-08-21T16:40:27.534805+00:00 [queued]>
[2024-08-21T16:41:29.584+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 7
[2024-08-21T16:41:29.600+0000] {taskinstance.py:2879} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-08-21 16:40:27.534805+00:00
[2024-08-21T16:41:29.609+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1399) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T16:41:29.611+0000] {standard_task_runner.py:72} INFO - Started process 1400 to run task
[2024-08-21T16:41:29.609+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_v2', 'insert_into_table', 'manual__2024-08-21T16:40:27.534805+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpnceffii1']
[2024-08-21T16:41:29.612+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask insert_into_table
[2024-08-21T16:41:29.665+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_v2.insert_into_table manual__2024-08-21T16:40:27.534805+00:00 [running]> on host 4bf35a2d5588
[2024-08-21T16:41:29.763+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='matea' AIRFLOW_CTX_DAG_ID='dag_with_postgres_v2' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T16:40:27.534805+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T16:40:27.534805+00:00'
[2024-08-21T16:41:29.764+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-21T16:41:29.787+0000] {sql.py:282} INFO - Executing: 
            insert into dag_runs(dt, dag_id) values ('2024-08-21', 'dag_with_postgres_v2')
            
[2024-08-21T16:41:29.798+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-08-21T16:41:29.808+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-08-21T16:41:29.816+0000] {sql.py:509} INFO - Running statement: 
            insert into dag_runs(dt, dag_id) values ('2024-08-21', 'dag_with_postgres_v2')
            , parameters: None
[2024-08-21T16:41:29.818+0000] {sql.py:518} INFO - Rows affected: 1
[2024-08-21T16:41:29.831+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-21T16:41:29.832+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_v2, task_id=insert_into_table, run_id=manual__2024-08-21T16:40:27.534805+00:00, execution_date=20240821T164027, start_date=20240821T164129, end_date=20240821T164129
[2024-08-21T16:41:29.878+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-21T16:41:29.896+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-21T16:41:29.898+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
